name: docker_image_download

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      image:
        description: "Docker image to download (e.g., nginx:latest)"
        required: true
        default: "nginx:latest"
      cleanup:
        description: "Whether to clean up disk space (true or false)"
        required: true
        default: "false"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Generate filename
        run: |
          IMAGE_NAME="${{ inputs.image }}"
          IMAGE_NAME_NO_TAG=$(echo "$IMAGE_NAME" | cut -d ':' -f1)
          TAR_NAME=$(echo "$IMAGE_NAME_NO_TAG" | sed 's#/#_#g').tar
          echo $TAR_NAME

      - name: Free Disk Space (Ubuntu)
        if: ${{ inputs.cleanup == 'true' }}
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Clone source code
        env:
          REPO_URL: https://github.com/NotGlop/docker-drag
          REPO_BRANCH: master
        run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH docker-drag

      - name: Download image
        working-directory: ./docker-drag
        run: |
          python3 docker_pull.py ${{ inputs.image }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TAR_NAME }}
          path: ./docker-drag/${{ env.TAR_NAME }}.tar
